[package]
name = "quic-rust"
version = "0.1.0"
authors = ["eb"]

[dependencies]

mio = "0.6"
bytes = "0.4"
quickcheck = "0.4"
rustls = "0.11.0"
webpki-roots = "0.13.0"
ring = { version = "0.12.1", features = ["rsa_signing"] }
webpki = { git = "https://github.com/briansmith/webpki" }
